# Generated by Django 4.2.7 on 2025-04-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationcode',
            name='raw_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
