# Generated by Django 4.2.4 on 2024-09-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_bitcoin_cash_wallet_user_bitcoin_wallet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bitcoin_cash_wallet',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bitcoin_wallet',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bnb_wallet',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dogecoin_wallet',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ethereum_wallet',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tether_usdt_trc20_wallet',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tron_wallet',
        ),
        migrations.RemoveField(
            model_name='user',
            name='usdt_erc20_wallet',
        ),
        migrations.AddField(
            model_name='user',
            name='Etherum_wallet',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Shiba_wallet',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Tether_erc20_wallet',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Bitcoin_cash_wallet',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Bitcoin_wallet',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Bnb_wallet',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Dogecoin_wallet',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Tether_usdt_trc20_wallet',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Tron_wallet',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Usdt_erc20_wallet',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
