# Generated by Django 4.2.7 on 2025-04-28 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_usdt_erc20_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usdt_erc20_wallet',
        ),
    ]
