# Generated by Django 4.2.7 on 2025-04-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_usdt_erc20_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usdt_erc20_wallet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
