# Generated by Django 5.1.2 on 2024-11-16 15:31

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_bitcoin_cash_wallet_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', account.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Bitcoin_cash_wallet',
            new_name='bitcoin_cash_wallet',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Bitcoin_wallet',
            new_name='bitcoin_wallet',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Bnb_wallet',
            new_name='bnb_wallet',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Dogecoin_wallet',
            new_name='dogecoin_wallet',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Etherum_wallet',
            new_name='ethereum_wallet',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Shiba_wallet',
            new_name='shiba_wallet',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Tether_erc20_wallet',
            new_name='tether_erc20_wallet',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Tether_usdt_trc20_wallet',
            new_name='tether_usdt_trc20_wallet',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Tron_wallet',
            new_name='tron_wallet',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Usdt_erc20_wallet',
            new_name='usdt_erc20_wallet',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
