# Generated by Django 5.1.3 on 2025-01-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransactionHistory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether'), ('BNB', 'Binance Coin'), ('DOGE', 'Dogecoin'), ('LTC', 'Litecoin'), ('TRC', 'Troncoin'), ('BCH', 'Bitcoin Cash'), ('SHIB', 'Shiba Coin')], max_length=10),
        ),
    ]
