# Generated by Django 4.2.7 on 2025-04-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReferralLinks', '0002_alter_referrallink_referred_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrallink',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
