# Generated by Django 4.2.7 on 2025-04-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReferralLinks', '0003_alter_referrallink_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrallink',
            name='referral_link',
            field=models.URLField(blank=True),
        ),
    ]
