# Generated by Django 5.1.3 on 2025-04-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReferralLinks', '0004_referrallink_referral_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referrallink',
            name='referral_link',
        ),
        migrations.AlterField(
            model_name='referrallink',
            name='referral_code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
