# Generated by Django 4.2.7 on 2025-04-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='user',
        ),
    ]
