# Generated by Django 4.2.7 on 2025-05-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
    ]
