# Generated by Django 4.2.4 on 2024-10-21 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address_sensitivity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('paranoid', 'Paranoid')], default='disabled', max_length=20)),
                ('detect_device_change', models.BooleanField(default=False)),
                ('email_verification_code', models.CharField(blank=True, max_length=8, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_browser', models.CharField(blank=True, max_length=200, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=6, null=True)),
                ('pin_expiration', models.DateTimeField(blank=True, null=True)),
                ('suspicious_login_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
