# Generated by Django 5.1.5 on 2025-03-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EditAccount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editaccount',
            name='wallet_address',
        ),
        migrations.RemoveField(
            model_name='editaccount',
            name='wallet_type',
        ),
        migrations.AddField(
            model_name='editaccount',
            name='bitcoin_cash_wallet',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='editaccount',
            name='bitcoin_wallet',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='editaccount',
            name='bnb_wallet',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='editaccount',
            name='dogecoin_wallet',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='editaccount',
            name='ethereum_wallet',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='editaccount',
            name='shiba_wallet',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='editaccount',
            name='tether_erc20_wallet',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='editaccount',
            name='tether_usdt_trc20_wallet',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='editaccount',
            name='tron_wallet',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='editaccount',
            name='usdt_erc20_wallet',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='editaccount',
            name='new_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
