# Generated by Django 5.1.5 on 2025-03-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EditAccount', '0003_remove_editaccount_bitcoin_cash_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='editaccount',
            name='bitcoin_cash_wallet',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
