# Generated by Django 4.2.7 on 2025-04-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EditAccount', '0005_accounteditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editaccount',
            name='usdt_erc20_wallet',
        ),
        migrations.AddField(
            model_name='editaccount',
            name='litecoin_wallet',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
